name: Comment on Professor Issue

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    # Only run if the issue has the "contact" label (from update professor details template)
    if: contains(github.event.issue.labels.*.name, 'contact')

    steps:
      - name: Add Approve/Reject instructions
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## Review Professor Details Update

            Please review the professor details update request above and choose an action by commenting on this issue:

            | Action | Command | Description |
            |--------|---------|-------------|
            | ✅ **Approve** | Comment: `approve` | Update professor details in database and close issue |
            | ❌ **Reject** | Comment: `reject` or `reject: [reason]` | Reject this update request and close issue |

            **Instructions:**
            - To **approve**: Simply comment `approve` on this issue
            - To **reject**: Comment `reject` or `reject: reason for rejection` on this issue
            - The workflows will run automatically when you comment
