name: Reject Contact

on:
  workflow_dispatch:
    inputs:
      issue:
        description: 'Issue number'
        required: true
      reason:
        description: 'Reason for rejection'
        required: false

jobs:
  reject:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue has "contact" label
        id: check-label
        run: |
          LABELS=$(gh issue view ${{ github.event.inputs.issue }} --json labels -q '.labels[].name')
          if echo "$LABELS" | grep -qw "contact"; then
            echo "has_contact=true" >> $GITHUB_ENV
          else
            echo "has_contact=false" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail if missing label
        if: env.has_contact != 'true'
        run: |
          echo "❌ Issue does not have the 'contact' label. Skipping."
          exit 1

      - name: Comment and Close
        run: |
          REASON=${{ github.event.inputs.reason }}
          if [ -z "$REASON" ]; then
            COMMENT="❌ Rejected by @${{ github.actor }}."
          else
            COMMENT="❌ Rejected by @${{ github.actor }}. Reason: $REASON"
          fi
          gh issue comment ${{ github.event.inputs.issue }} --body "$COMMENT"
          gh issue close ${{ github.event.inputs.issue }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
