name: Reject Professor Details Update

on:
  issue_comment:
    types: [created]

jobs:
  reject:
    runs-on: ubuntu-latest
    # Only run if comment starts with "reject" and issue has "contact" label
    if: |
      startsWith(github.event.comment.body, 'reject') &&
      contains(github.event.issue.labels.*.name, 'contact') &&
      github.event.issue.state == 'open'

    steps:
      - name: Extract rejection reason
        id: extract-reason
        run: |
          COMMENT="${{ github.event.comment.body }}"
          # Extract reason after "reject:" or "reject "
          if [[ "$COMMENT" == *":"* ]]; then
            REASON=$(echo "$COMMENT" | sed 's/reject: *//' | xargs)
          elif [[ "$COMMENT" != "reject" ]]; then
            REASON=$(echo "$COMMENT" | sed 's/reject *//' | xargs)
          else
            REASON=""
          fi
          echo "reason=$REASON" >> $GITHUB_OUTPUT
          echo "Extracted reason: '$REASON'"

      - name: Add rejection comment and close issue
        run: |
          REASON="${{ steps.extract-reason.outputs.reason }}"

          if [ -z "$REASON" ] || [ "$REASON" = "" ]; then
            COMMENT="**Rejected by @${{ github.event.comment.user.login }}**

          This professor details update request has been rejected.

          This issue is now closed."
          else
            COMMENT="**Rejected by @${{ github.event.comment.user.login }}**

          This professor details update request has been rejected.

          **Reason:** $REASON

          This issue is now closed."
          fi

          gh issue comment ${{ github.event.issue.number }} --body "$COMMENT"
          gh issue close ${{ github.event.issue.number }} --reason "not planned"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
