name: Reject Contact

on:
  workflow_dispatch:
    inputs:
      issue:
        description: 'Issue number'
        required: true
      reason:
        description: 'Reason for rejection'
        required: false

jobs:
  reject:
    if: contains(github.event.issue.labels.*.name, 'contact')
    runs-on: ubuntu-latest

    steps:
      - name: Comment and Close
        run: |
          REASON=${{ github.event.inputs.reason }}
          if [ -z "$REASON" ]; then
            COMMENT="❌ Rejected by @${{ github.actor }}."
          else
            COMMENT="❌ Rejected by @${{ github.actor }}. Reason: $REASON"
          fi
          gh issue comment ${{ github.event.inputs.issue }} --body "$COMMENT"
          gh issue close ${{ github.event.inputs.issue }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
